### builtin configuration for arrays
#
#  access or overwrite using nested builtin context e.g.
#  builtin:
#    textile:
#        libs: [ whatever ]


# text filters

filters:
  - comments-percent-style
  - skip-end-directive
  - include-helper-hack
  - erb
  - code-block-curly-style 
 

# markup (textile, markdown) config
    
textile:
  extnames: [ .textile, .t ]
  
markdown:
  extnames: [ .markdown, .m, .mark, .mkdn, .md, .txt, .text ]

# note: only kramdown is listed as a dependency in gem specs (because it's Ruby only and, thus, easy to install)
#  if you want to use other markdown libs install the required/desired lib e.g.
#  use  gem install rdiscount for rdiscount and so on
#
# also note for now the first present markdown library gets used
#  the search order is first come, first serve, that is: rdiscount, rpeg-markdown, maruku, bluecloth, kramdown (fallback, always present)

  libs:
    - rdiscount
    - rpeg-markdown
    - maruku
    - bluecloth
    - kramdown
    